### ISSUE TITLE
Code string breaks weirdly

### ISSUE THREAD

**Issue by SimenB** [jest-website-migration/jest#4]
![Screenshot_20201204-132809](https://user-images.githubusercontent.com/1404810/101163894-9ae79680-3634-11eb-9228-67be19328a86.png)

Avoiding the newline if possible would be nice here

**Comment by orta** [comment]
This is (probably) from:

```css
.markdown li, body {
word-wrap: break-word;
}
```

I think an overwrite for just the index page would be fine in this case
