### ISSUE TITLE
Switch nav logo to [ JEST ]

### ISSUE THREAD

**Issue by orta** [jest-website-migration/jest#5]
![Screen Shot 2020-12-04 at 12 32 36 PM](https://user-images.githubusercontent.com/49038/101164339-d2eadb80-362c-11eb-9c6b-35cf25d240a6.png)
  Should ideally be switched to:
  ![Screen Shot 2020-12-04 at 12 33 23 PM](https://user-images.githubusercontent.com/49038/101164422-eac25f80-362c-11eb-96b9-24d5a8b15719.png)
  Could just be done in CSS on the "Jest" text, e.g something like

```css
.fixedHeaderContainer header .headerTitleWithLogo {
  display: block;
  font-size: 1.25em;
  line-height: 18px;
  margin: 0;
  position: relative;
  z-index: 9999;
}

.headerTitleWithLogo {
  background-color: var(--green);
  text-transform: uppercase;
  color: var(--grey2);
  padding: 6px 15px;
}
```
